[package]
name = "eous"
version = "0.1.0"
description = "EOUS desktop application"
authors = ["EOUS"]
edition = "2021"

[lib]
name = "eous_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1.0.150"
tauri = { version = "2", features = [] }
tauri-plugin-sql = { version = "2.4.0", features = ["sqlite"] }
